language: r

matrix:
  include:
    - os: linux
      r: release
      r: devel
    - os: osx
      r: release
      env: COVERALLS_TEST=true
      disable_homebrew: true

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo


sudo: false
cache: packages
warnings_are_errors: true

r_github_packages:
    - hadley/testthat
    - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [ "${COVERALLS_TEST}" ]; then Rscript -e 'covr::coveralls()'; fi
